import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Nika",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Bohemian TearDrop Earrings",
      productTag: "bohemian-teardrop-earrings",
      category: "Jewelry",
      image: "/images/p1.jpg",
      price: 15,
      countInStock: 0,
      brand: "ZukaJewls",
      rating: 4.5,
      numReviews: 10,
      description:
        "High-quality picture is printed on waterproof paper and protected with a glass cabochon. All findings are Nickel Free.",
    },
    {
      //_id: "2",
      name: "Flowers dangle earrings",
      productTag: "flowers-dangle-earrings",
      category: "Jewelry",
      image: "/images/p2.jpg",
      price: 21,
      countInStock: 20,
      brand: "ZukaJewls",
      rating: 4.0,
      numReviews: 10,
      description:
        "High-quality picture is printed on waterproof paper and protected with a glass cabochon. All findings are Nickel Free.",
    },
    {
      //_id: "3",
      name: "Green TearDrop Earrings",
      productTag: "green-teardrop-earrings",
      category: "Jewelry",
      image: "/images/p3.jpg",
      price: 11,
      countInStock: 15,
      brand: "ZukaJewls",
      rating: 4.5,
      numReviews: 14,
      description:
        "These earrings are available as screw in clip on earrings or for pierced ear, (select the style when ordering from the drop down bar). High-quality picture is printed on waterproof paper and protected with a glass cabochon. All findings are Nickel Free.",
    },
    {
      //_id: "4",
      name: "Leather Dog Collar",
      productTag: "leather-dog-collar",
      category: "Pet Supplies",
      image: "/images/p4.jpg",
      price: 15,
      countInStock: 5,
      brand: "BronzeDog",
      rating: 4.5,
      numReviews: 10,
      description:
        "Collars are made of full grain cowhide leather on top and soft padded leather base. We use high quality buckle (shape of the buckle may vary) and very strong D ring. We make these collars in two basic tops: Black top and Brown top. You can choose from drop down menu best color combination. We make these collars in 4 sizes. Collars are supplied with solid brass nameplate.",
    },
    {
      //_id: "5",
      name: "Carstens Ceramic Vase",
      productTag: "carstens-ceramic-vase",
      category: "Vases",
      image: "/images/p5.jpg",
      price: 34,
      countInStock: 12,
      brand: "OberSchick",
      rating: 2.5,
      numReviews: 55,
      description:
        "Great vase of Carstens pottery from the 70s. Hand flattering blue/black matte glaze. Super shape with a very nice décor. Good undamaged vintage condition. Ground mark: W.Germany 3-25. Height: 25 cm ",
    },
    {
      //_id: "6",
      name: "Bougainvilleas Wall Art",
      productTag: "bougainvilleas-wall-art",
      category: "Wall decor",
      image: "/images/p6.jpg",
      price: 4,
      countInStock: 40,
      brand: "StarPaintTwoD",
      rating: 4.5,
      numReviews: 51,
      description:
        "Digital Printable File, Instant Download. After your purchase you will receive an email from etsy with the below 4 JPG files in RGB 300dpi : 1. Aspect ratio 2x3 suitable for printing: 12x18 inc / 30x45cm. 8x12 inc / 20x30cm. 4x6 inc / 10x15cm",
    },
    {
      //_id: "7",
      name: "40cm Wooden Lamp Design",
      productTag: "40cm-wooden-lamp-design",
      category: "Lighting",
      image: "/images/p7.jpg",
      price: 210,
      countInStock: 150,
      brand: "ArtByRoses",
      rating: 3.5,
      numReviews: 146,
      description:
        "Design lighting in varnished exotic wood. 40 cm diameter, 30cm high, (bulb E27, preferably opaque) Artisanal manufacturing with laser cutting. This luminaire gives a soft and subdued lighting, it creates a warm atmosphere, the shadow of the leaves is reflected on the ceiling. Ideal for one bedroom.",
    },
    {
      //_id: "8",
      name: "Mid Century Modern Wooden Lamp",
      productTag: "Mid Century Modern Wooden Lamp",
      category: "Lighting",
      image: "/images/p8.jpg",
      price: 160,
      countInStock: 400,
      brand: "ArtByRoses",
      rating: 4,
      numReviews: 58,
      description:
        "This handmade wood pendant light combines contemporary industrial design with a mid-century modern feeling. What is so unique about this lamp is the fact that it creates streams of shadow and light on the ceiling and walls. The stronger the light, the bigger the casting shadows. Like a modern chandelier, it would fit perfectly in every room emphasizing how geometry and modern art could provide a warm lighting environment. Our customers have stated that it looks like an absolute “piece of jewelry”.",
    },
    {
      //_id: "9",
      name: "Frida Kahlo Crochet Doll",
      productTag: "frida-kahlo-crochet-doll",
      category: "Toys",
      image: "/images/p9.jpg",
      price: 22,
      countInStock: 14,
      brand: "Zeylum",
      rating: 2.5,
      numReviews: 5,
      description:
        "Introducing our 11-inch Frida Kahlo inspired crochet cotton stuffed doll! This unique and beautiful doll is a perfect tribute to the iconic Mexican painter and surrealist icon, Frida Kahlo. Frida Kahlo was a self-taught artist, who is best known for her vivid self-portraits that reflect her strong feelings. Her works of art not only offer a glimpse into her personal life but also showcase the cultural heritage of Mexico. Our doll is designed to capture the essence of Frida Kahlo, with her signature vibrant shawl, and distinctive eyebrows.",
    },
    {
      //_id: "10",
      name: "Oval Wood Earring Copper Tear",
      productTag: "oval-wood-earring-copper-tear",
      category: "Jewelry",
      image: "/images/p10.jpg",
      price: 19,
      countInStock: 48,
      brand: "ZukaJewls",
      rating: 1.5,
      numReviews: 15,
      description:
        "Since my Earrings are made to order from natural and unique gemstones, they might appear slightly different than on the pictures. Please feel free to ask for a picture of your order for approval before shipment. All the Jewelry are cleaned with Sage before the shipping. Earring made with a stained wood oval and a printed antique copper teardrop. Total size is 3 inches. The clip is made of antique copper.",
    },
    {
      //_id: "11",
      name: "Bamboo Pendant Light",
      productTag: "Bamboo Pendant Light",
      category: "Lighting",
      image: "/images/p11.jpg",
      price: 28,
      countInStock: 150,
      brand: "ArtByRoses",
      rating: 3,
      numReviews: 60,
      description:
        "The basket is compressible/expandable like a concertina and can achieve many shapes and position - the oblong shape is the natural position/shape - the round shapes as shown in the listing pictures for example are achieved simply by compressing from each end, and tying the supplied string inside to pull taut as shown to then hold in desired position. e.g The third picture shows standard oblong baskets, one of which has been made into a round ball shape.",
    },
    {
      //_id: "12",
      name: "Field Of Flowers Art Canvas",
      productTag: "field-of-flowers-art-canvas",
      category: "Wall decor",
      image: "/images/p12.jpg",
      price: 65,
      countInStock: 4,
      brand: "StarPaintTwoD",
      rating: 5,
      numReviews: 20,
      description:
        "Extra Large Vintage Flower Field Landscape Tapestry. Easily fill up a large amount of wall space with our oversized tapestries. Available in 6 sizes (shown below and in the drop down menu). Our hanging tapestry is printed on 100% cotton canvas. Frames are made of pine and are naturally lightweight. Very easy to hang with two attached sawtooth hangers.",
    },
    {
      //_id: "13",
      name: "Folk Pendant Necklace",
      productTag: "folk-pendant-necklace",
      category: "Jewelry",
      image: "/images/p13.jpg",
      price: 12,
      countInStock: 46,
      brand: "ZukaJewls",
      rating: 3,
      numReviews: 10,
      description:
        "Select from an Antique Bronze or Shiny Silver finish. High-quality picture is printed on waterproof paper and protected with a glass cabochon. All findings are Nickel Free.",
    },
    {
      //_id: "14",
      name: "Personalized Dog Leash Leather",
      productTag: "personalized-dog-leash-leather",
      category: "Pet Supplies",
      image: "/images/p14.jpg",
      price: 32,
      countInStock: 89,
      brand: "BronzeDog",
      rating: 3.5,
      numReviews: 67,
      description:
        "The walks in the park will literally feel different, as this high-quality leather's contact with your hand is something that needs to be experienced. Time and use only add to this feeling as it is the material's characteristic to become more personal after use. Add the personalized, exclusively handcrafted name plate and you have something truly one-of-a-kind!",
    },
    {
      //_id: "15",
      name: "Rattan Woven Vase",
      productTag: "rattan-woven-vase",
      category: "Vases",
      image: "/images/p15.jpg",
      price: 32,
      countInStock: 19,
      brand: "OberSchick",
      rating: 4.5,
      numReviews: 3,
      description:
        "This product is a woven flower vase, it looks very beautiful. Made with premium material, so this product is durable, and you can use it for a long time. Suitable for wedding flower and also decorating your room. Putting some beautiful flowers, it is an attractive gift for your receivers. It can be put in your living room, bedroom, office, and so on. As a decoration for yourself or a gift to friends.",
    },
    {
      //_id: "16",
      name: "Waldorf Custom Doll",
      productTag: "waldorf-custom-doll",
      category: "Toys",
      image: "/images/p16.jpg",
      price: 83,
      countInStock: 200,
      brand: "Zeylum",
      rating: 5,
      numReviews: 157,
      description:
        "Introducing our handmade organic Waldorf doll, made with safe and natural materials for your child's imaginative play. Our doll is designed with a soft cotton body and wool hair, encouraging imaginative play and connection with nature. The doll is safe for children of all ages and its natural materials are gentle on skin. Every detail is thoughtfully crafted, the face is hand-painted and features are embroidered, making each doll unique. The wool stuffing provides a nice weight, making it easy to hug and cuddle. The wool hair is also soft and easy to style, making it perfect for children who love to play hairdresser.",
    },
    {
      //_id: "17",
      name: "Wood Pendant Ceiling Light",
      productTag: "wood-pendant-ceiling-light",
      category: "Lighting",
      image: "/images/p17.jpg",
      price: 115,
      countInStock: 38,
      brand: "ArtByRoses",
      rating: 4,
      numReviews: 7,
      description:
        "Our “mineral” chandelier is an epitome of industrial aesthetic combined with modern contemporary art and geometry mixing wood and plexiglass together. This lamp provides a very specific effect on the walls and could totally transform your bedroom and your dining room. It is made of Veneered Oak MDF, an excellent quality real oak wood that is bonded to MDF providing iconic natural grains. Exceptional characteristics of stability, durability, and maintenance in time distinguished it.",
    },
    {
      //_id: "18",
      name: "Floral Embroidery Kit",
      productTag: "floral-embroidery-kit",
      category: "Fiber Arts",
      image: "/images/p18.jpg",
      price: 20,
      countInStock: 32,
      brand: "Zazarita",
      rating: 3.5,
      numReviews: 77,
      description:
        "This hand embroidery kit will include everything you need to start the project and it is a great Kit for Beginners too! These embroidery kits are the best gifts for mom , sewing lovers and embroidery lovers, a great present for Christmas and the mothers day.",
    },
    {
      //_id: "19",
      name: "Wool Moroccan Rug",
      productTag: "Wool Moroccan Rug",
      category: "Fiber Arts",
      image: "/images/p19.jpg",
      price: 870,
      countInStock: 28,
      brand: "Zazarita",
      rating: 4,
      numReviews: 217,
      description:
        "These vintage rugs from boujaad are probably the most comfortable vintage rugs you will ever come across. They are made from 100% sheep's wool and are 100% undyed. These handmade rugs are made for those who truly appreciate the natural world. They are the epitome of warmth and luxury. All Azilal rugs share a signature style with geometric patterns. It is a classic design for any room. You will also see symbols. They tell true stories of each weaver's life.",
    },
    {
      //_id: "20",
      name: "Needle Felted Blue Tit",
      productTag: "needle-felted-blue-tit",
      category: "Fiber Arts",
      image: "/images/p20.jpg",
      price: 28,
      countInStock: 391,
      brand: "Zazarita",
      rating: 4.5,
      numReviews: 10,
      description:
        "This Cute Little Bluetit is needle felted. His body and beak are made of natural wool and he has black beads for eyes. He measures approx 4,5 (11 cm) from beak to tail.",
    },
    {
      //_id: "21",
      name: "Leather cover for Leuchtturm",
      productTag: "leather-cover-for-leuchtturm",
      category: "Books",
      image: "/images/p21.jpg",
      price: 27,
      countInStock: 0,
      brand: "LeatherBookMaker",
      rating: 4.5,
      numReviews: 67,
      description:
        "Simple design leather cover for LEUCHTTURM1917 NOTEBOOK MEDIUM (A5) , this slim notebook cover was made of high quality cow leather, 100% hand sewn using saddle stitch , slit cut for elastic band. we also could engrave something on it if you like.",
    },
    {
      //_id: "22",
      name: "Vintage Photo Album",
      productTag: "vintage-photo-album",
      category: "Books",
      image: "/images/p22.jpg",
      price: 39,
      countInStock: 40,
      brand: "LeatherBookMaker",
      rating: 5,
      numReviews: 9,
      description:
        "The handmade album scrapbook with genuine leather, the best gift for you and your loved ones, an ideal gift for Valentine's Day, Mother's Day, Father's Day, Christmas, Wedding, Birthday, Graduation or Anniversary, which will become a very wonderful memory.",
    },
    {
      //_id: "23",
      name: "Teardrop Earrings With Birds",
      productTag: "teardrop-earrings-with-birds",
      category: "Jewelry",
      image: "/images/p23.jpg",
      price: 11,
      countInStock: 99,
      brand: "ZukaJewls",
      rating: 1.5,
      numReviews: 11,
      description:
        "These earrings are available as screw in clip on earrings or for pierced ear, (select the style when ordering from the drop down bar). High-quality picture is printed on waterproof paper and protected with a glass cabochon. All findings are Nickel Free.",
    },
    {
      //_id: "24",
      name: "Abstract Colorful Oil Painting",
      productTag: "abstract-colorful-oil-painting",
      category: "Wall decor",
      image: "/images/p24.jpg",
      price: 115,
      countInStock: 39,
      brand: "StarPaintTwoD",
      rating: 3.5,
      numReviews: 132,
      description:
        "Unframed/Not stretched. Not Ready to Hang. Rolled Canvas sent with 2 inches border for framing. MADE-TO-ORDER painting and be Customizable whatever you want. (size, color, etc.). Abstract Colorful Textured Oil Painting on Canvas, Large Minimalist Original Handmade Acrylic Painting Modern Wall Art Living Room Home Decor",
    },
    {
      //_id: "25",
      name: "Luxury Ceramic Vases",
      productTag: "luxury-cramic-vases",
      category: "Vases",
      image: "/images/p25.jpg",
      price: 49,
      countInStock: 65,
      brand: "OberSchick",
      rating: 1,
      numReviews: 2,
      description:
        "Set of 2 Luxury Minimalistic Ceramic Vases - Available to purchase separately. Set a new tone to your living space and will be the best choice for gifting to your loved ones.",
    },
    {
      //_id: "26",
      name: "Engraved Notebook Personalized",
      productTag: "engraved-notebook-personalized",
      category: "Books",
      image: "/images/p26.jpg",
      price: 8,
      countInStock: 20,
      brand: "LeatherBookMaker",
      rating: 4.5,
      numReviews: 72,
      description:
        "These notebooks are great for recording your experiences, ideas and time. Some other applications include a travel journal, a cook book for recipes, a devotional or even tracking your exercise/training progress.",
    },
    {
      //_id: "27",
      name: "Metalwork Embroidery Fox Kit",
      productTag: "metalwork-embroidery-fox-kit",
      category: "Fiber Arts",
      image: "/images/p27.jpg",
      price: 51,
      countInStock: 83,
      brand: "Zazarita",
      rating: 3.5,
      numReviews: 87,
      description:
        "In this kit you can make a cute Fox design, embroidered in 3 Metalwork techniques over 3 layers of felt padding. The Fox is worked in Metalwork embroidery, a technique seen throughout history on pieces such as haute couture garments, ceremonial and military dress, and ecclesiastical furnishings. Its richness and opulence was a symbol of wealth and power, and fine examples can be seen on the Queens coronation robe as well as high fashion today.",
    },
    {
      //_id: "28",
      name: "3D Printed Articulated Dragon",
      productTag: "3d-printed-articulated-dragon",
      category: "Toys",
      image: "/images/p28.jpg",
      price: 47,
      countInStock: 221,
      brand: "Zeylum",
      rating: 2,
      numReviews: 6,
      description:
        "We assemble Braq with elastic string as tightly as possible so that it will hold it's pose. We use a special method so that it will hold it's pose much better than others. Spotless clean. Quality print. Will be shipped in a BOX to avoid any damage during shipping.",
    },
    {
      //_id: "29",
      name: "Bonsai Rustic Decor Light",
      productTag: "bonsai-rustic-decor-light",
      category: "Lighting",
      image: "/images/p29.jpg",
      price: 19,
      countInStock: 100,
      brand: "ArtByRoses",
      rating: 5,
      numReviews: 432,
      description:
        "Inspired by growing up with big trees this night light is perfect for bedrooms, nurseries, bathrooms, hallways, kitchens, corridor and more! Choose Standard or Deluxe. Standard - Night Light has only the Front Plate Design. Deluxe - Night Light has Sides with Detailed Designs on it.",
    },
    {
      //_id: "30",
      name: "Personalised Dog Collar",
      productTag: "personalised-dog-collar",
      category: "Pet Supplies",
      image: "/images/p30.jpg",
      price: 25,
      countInStock: 991,
      brand: "BronzeDog",
      rating: 3.5,
      numReviews: 239,
      description:
        "My aim is to offer to our four legged best friends stylish and comfortable handmade leather collars for secure walks! Such as these gorgeous leather dog collars handcrafted in my workshop completely by hand with lots of love and attention to details. The patterns are cut by hand and hand punched without the use of any machines or electricity. This kind of leather is incredibly durable, flexible and really strong for every breed.",
    },
    {
      //_id: "31",
      name: "Refillable Leather Journal",
      productTag: "refillable-leather-journal",
      category: "Books",
      image: "/images/p31.jpg",
      price: 46,
      countInStock: 75,
      brand: "LeatherBookMaker",
      rating: 2.5,
      numReviews: 87,
      description:
        "Passport model(3.5'X4.9') Personal model(3.8' x 6.5') Standard (4.6'X8.3' ),A5 (5.6'x8.3'), perfect size to carry with you. The journal have three books aout72sheets/ 144pages, Tough rustic leather protects your creations. Leather wrap closure",
    },
    {
      //_id: "32",
      name: "Chicks Crocheted in Eggs",
      productTag: "chicks-crocheted-in-eggs",
      category: "Fiber Arts",
      image: "/images/p32.jpg",
      price: 10,
      countInStock: 41,
      brand: "Zazarita",
      rating: 3,
      numReviews: 18,
      description:
        "Crochet chicks with shells, in many bright colors! For the approaching Easter, they can be suitable as a place card, to color the table, as a keychain, a gift idea with lots of chocolate eggs! Created in crochet, in fine thread, with bead eyes, with bio padding! Approximately 10 cm in height This is a finished product !! In gift box with flower as shown in the photo.",
    },
    {
      //_id: "33",
      name: "Abstract Gold Foil Painting",
      productTag: "abstract-gold-foil-painting",
      category: "Wall decor",
      image: "/images/p33.jpg",
      price: 89,
      countInStock: 3,
      brand: "StarPaintTwoD",
      rating: 4,
      numReviews: 67,
      description:
        "This painting is an original, abstract, high-quality 100% hand-painted oil/acrylic painting on canvas. This wall hanging will look beautiful as office decor, home decor, in any lobby or building, or even in the bedroom, living room, or children's room decor. Here you can find any painting you want. If you like our artworks, please favorite my works and store them, we'll keep updating our artworks here.",
    },
    {
      //_id: "34",
      name: "Origami Lamp Moth White",
      productTag: "origami-lamp-moth-white",
      category: "Lighting",
      image: "/images/p34.jpg",
      price: 57,
      countInStock: 221,
      brand: "ArtByRoses",
      rating: 4.5,
      numReviews: 127,
      description:
        "The strong folds play with the light. The lamp gives smooth, cozy light. It is very suitable for above the dining table for everyday use or for use in your living room, bedroom or nursery. The lampshade fits around a standard energy-saving lightbulb or LED lightbulb. We recommend a LED lightbulb which is better for nature because there is no mercury in LED lightbulbs.",
    },
    {
      //_id: "35",
      name: "Green Wooden Ring",
      productTag: "green-wooden-ring",
      category: "Jewelry",
      image: "/images/p35.jpg",
      price: 61,
      countInStock: 23,
      brand: "ZukaJewls",
      rating: 4,
      numReviews: 76,
      description:
        "When ordering, specify the width of the ring and the shape of the ring !!! The price is for 1 ring! We present to you a truly unique and enchanting jewel with a touch of modern style. Plus, it is a perfectly fashionable minimalistic accessory to any outfit which will add special charm to your natural beauty. These wooden rings have been crafted from carefully selected wood and inlaid with real Flower green hydrangea, mint, moss, 24K Gold.",
    },
    {
      //_id: "36",
      name: "Keulse Pot Vase",
      productTag: "keulse-pot-vase",
      category: "Vases",
      image: "/images/p36.jpg",
      price: 16,
      countInStock: 12,
      brand: "OberSchick",
      rating: 2,
      numReviews: 8,
      description:
        "Typical vase from Cologne (West-Germany). Made of stone and painted with beautiful blue. In mint condition.",
    },
    {
      //_id: "37",
      name: "Soft Bright Stuffed Doll",
      productTag: "soft-bright-stuffed-doll",
      category: "Toys",
      image: "/images/p37.jpg",
      price: 29,
      countInStock: 330,
      brand: "Zeylum",
      rating: 4.5,
      numReviews: 170,
      description:
        "Bright doll, Soft doll, Stuffed doll, Cloth doll, Plush doll. This Tilda is made of natural materials, cotton. Height of 12 inches (30 cm). This is an art doll. All faces are hand painted by akvarel pencil. Do not wash in water!!! Hair for doll is made of yarn and is sewn in the middle. And is glued on the sides.",
    },
    {
      //_id: "38",
      name: "St. Patrick's Day Dog Hat",
      productTag: "st-patricks-day-dog-hat",
      category: "Pet Supplies",
      image: "/images/p38.jpg",
      price: 26,
      countInStock: 21,
      brand: "BronzeDog",
      rating: 3,
      numReviews: 80,
      description:
        "The hat was intended to serve as a cute holiday photo prop. It is held in place by a small elastic chin strap. The elastic chord is firm but stretchy so as to fit a larger variety of dog breeds and sizes. Because of this though, there are no ear straps on this version of my hat. Tip: Try the hat on your pet several times before your photo opp to help him/her get used to it. Be sure to bring lots of rewards!",
    },
    {
      //_id: "39",
      name: "French Bulldog Sweater",
      productTag: "french-bulldog-sweater",
      category: "Pet Supplies",
      image: "/images/p39.jpg",
      price: 27,
      countInStock: 11,
      brand: "BronzeDog",
      rating: 3.5,
      numReviews: 12,
      description:
        "Merino wool, being isothermal, absorbs moisture from the body, treats osteoarticular, neglected rheumatic and post-traumatic pains. Merino wool is considered curative in all countries of the world. It comes from Australia, it is EXTRA FINE 18 micron quality. It is soft like cashmere, does not irritate the skin, does not cause itching, and is anti-allergic. Machine washable with the wool program.",
    },
    {
      //_id: "40",
      name: "Red Flower Abstract Painting",
      productTag: "red-flower-abstract-painting",
      category: "Wall decor",
      image: "/images/p40.jpg",
      price: 360,
      countInStock: 63,
      brand: "StarPaintTwoD",
      rating: 4.5,
      numReviews: 441,
      description:
        "Original abstract paintings for your home decor. This art is a acrylic painting create with a palette knife. The flowers are in 3D / impasto art design. My paintings are for your home, office, hotel and practice. I paint paintings from the small size 24' to the largest size 90'. Customer orders are welcome. All paintings are ready to hang. A signed Certificate Of Authenticity will be included with every painting.",
    },
    {
      //_id: "41",
      name: "Just Hemp Rope Dog Leash",
      productTag: "just-hemp-rope-dog-leash",
      category: "Pet Supplies",
      image: "/images/p41.jpg",
      price: 27,
      countInStock: 118,
      brand: "BronzeDog",
      rating: 4,
      numReviews: 99,
      description:
        "Wigglywoo's Hemp Rope Leash is made from 1/2' (12 mm) 3-strand hemp rope, no dyes or other chemicals. Each leash is individually made, hand-spliced and whipped. Hemp rope is soft to the hand, yet strong and durable. It is a great leash for large dogs.",
    },
    {
      //_id: "42",
      name: "Amethyst Flower Earrings",
      productTag: "amethyst-flower-earrings",
      category: "Jewelry",
      image: "/images/p42.jpg",
      price: 39,
      countInStock: 8,
      brand: "ZukaJewls",
      rating: 2.5,
      numReviews: 10,
      description:
        "Amethyst flower earrings with vintage floral caps, violet flowers and purple amethyst crystal dangle drops. Beautiful for a bohemian nature inspired wedding or as a gift for her. Very pretty earrings. The gentle breeze gives these light airy earrings a fluid movement that creates a true sense of freedom as they dangle and swing in the fresh air. So irresistibly feminine and lightweight you will forget you are wearing them. Warning, these flirty earrings will attract many compliments ;)",
    },
    {
      //_id: "43",
      name: "Driftwood Floor Lamp",
      productTag: "driftwood-floor-lamp",
      category: "Lighting",
      image: "/images/p43.jpg",
      price: 435,
      countInStock: 63,
      brand: "ArtByRoses",
      rating: 4.5,
      numReviews: 76,
      description:
        "Driftwood floor lamp, Driftwood lighting,Driftwood beach decor. Uniquely handmade modern driftwood floor lamp with elegant design. The full transformation process of driftwood from the Greek shores of the Aegean sea, a sea arm of the Mediterranean, into this beautiful one-of-a-kind driftwood art is the result of many hours of love. This driftwood lamp brings the Ocean and nature's beauty inside with its amazing, exquisite design and is in harmony with every style house.",
    },
    {
      //_id: "44",
      name: "Vintage Tonala Vase",
      productTag: "vintage-tonala-vase",
      category: "Vases",
      image: "/images/p44.jpg",
      price: 26,
      countInStock: 1,
      brand: "OberSchick",
      rating: 3,
      numReviews: 2,
      description:
        "Beautiful vintage signed Mexican Tonala pottery vase. Vase stand approx 6.5' tall and is signed by the artist Gardiel. In very good condition no chips or cracks.",
    },
    {
      //_id: "45",
      name: "Spring Friends Pattern",
      productTag: "spring-friends-pattern",
      category: "Toys",
      image: "/images/p45.jpg",
      price: 15,
      countInStock: 5,
      brand: "Zeylum",
      rating: 4,
      numReviews: 13,
      description:
        "I created this pattern to celebrate Spring, my favourite time of year! The pattern includes instructions to make an adorable bunny or kitty as well as a couple of different outfits and accessories such as a sweet little summer dress, a cute pair of shorts with buttons and suspenders, a faux fur cape tied in front with a bow and a scarf.",
    },
    {
      //_id: "46",
      name: "Tea Cosy 4-6 Cup",
      productTag: "tea-cosy-4-6-cup",
      category: "Fiber Arts",
      image: "/images/p46.jpg",
      price: 17,
      countInStock: 95,
      brand: "Zazarita",
      rating: 5,
      numReviews: 44,
      description:
        "Hand knitted tea cosy in gorgeous acrylic/wool mix yarn. Embellished with white flowers and polka dot buttons. Available in succulent and cream yarn. Other colours available in my shop LittleDaisy Knits. This tea cosy is a perfect gift for a tea lover. Will keep your tea lovely and warm for longer. Hand wash, reshape whilst damp",
    },
    {
      //_id: "47",
      name: "Needle Felted Goldfinch",
      productTag: "needle-felted-goldfinch",
      category: "Fiber Arts",
      image: "/images/p47.jpg",
      price: 25,
      countInStock: 3,
      brand: "Zazarita",
      rating: 3.5,
      numReviews: 24,
      description:
        "Felting is the activity of making wool into felt, and is one of the oldest forms of textile arts. Each bird is felted with 100% natural corriedale carded wool. The wool is shaped using felting needles and punches that slowly weave the fibers together. Each piece is refined and then attached to create a full figure. After thoughtful consideration of color, shape and personality a new friend is born! With your purchase you will receive a one of a kind felted friend, an adoption certificate, and a small natural aspen wood nest.",
    },
    {
      //_id: "48",
      name: "Ancient Islamic Painting",
      productTag: "ancient-islamic-painting",
      category: "Wall decor",
      image: "/images/p48.jpg",
      price: 12,
      countInStock: 11,
      brand: "StarPaintTwoD",
      rating: 5,
      numReviews: 7,
      description:
        "This stunning piece of art showcases the grandeur and magnificence of an ancient mosque, with intricate details that will leave you in awe. Our expertly crafted digital painting captures the essence of Islamic architecture, featuring intricate patterns, arches, and domes that are true to the original structure. The warm and inviting color palette adds to the overall charm of the artwork, making it an ideal addition to any room in your home.",
    },
    {
      //_id: "49",
      name: "Pumpkin Cat Hat",
      productTag: "pumpkin-cat-hat",
      category: "Pet Supplies",
      image: "/images/p49.jpg",
      price: 13,
      countInStock: 6,
      brand: "BronzeDog",
      rating: 3.5,
      numReviews: 18,
      description:
        "Want your little pumpkin to dress up for the fall holidays this year? This fun little pumpkin hat would make a great autumn accessory for both Halloween and Thanksgiving. These hats come in sizes perfect to fit your kitten, cat, or small dog. Each hat has 2 ear holes, some dangly green 'vines' (that also serve as tie straps to secure hat) and a little stem and leaf on top.",
    },
    {
      //_id: "50",
      name: "Orange Sphere Lapm",
      productTag: "orange-sphere-lapm",
      category: "Lighting",
      image: "/images/p50.jpg",
      price: 93,
      countInStock: 55,
      brand: "ArtByRoses",
      rating: 4.5,
      numReviews: 60,
      description:
        "Orange sphere. Modern pendant lamp. Globe pendant light. Lighting fixture. Ball shadow lamp. Bedroom light fixture. Ceiling lamp, orange lamp, design lamp, Ceiling lamp, Office light, kitchen lamp (30cm-12') The light from this yarn pendant looks amazing in the room and it is environmentally friendly as well! It is an Eco-friendly light for your house. This beautiful turquoise string light will bring a natural accent to any style room. It is handmade and every piece is unique.",
    },
  ],
};

export default data;
